### PR TITLE
Feature/emoji validation

### PR DESCRIPTION
**Pull request by DeeDowns**
# Description
Fixed issue with comma being taken into account for an emoji string. This was preventing the emoji string from passing the check and resulting in 403 error and vote not being submitted

Fixes #

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [x] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Review by gregory-j-wilson — DISMISSED** [review]
sounds good.

**Review by ajg7 — APPROVED** [review]
Looks good

**Review by gregory-j-wilson — APPROVED** [review]
cool

**Review by gregory-j-wilson — APPROVED** [review]
cool

**Pull request merged**
